<script src="<?php echo APP::config('url'); ?>public/js/vendor/jquery.js"></script>
<script src="<?php echo APP::config('url'); ?>public/js/vendor/what-input.js"></script>
<script src="<?php echo APP::config('url'); ?>public/js/vendor/foundation.js"></script>
<script src="<?php echo APP::config('url'); ?>public/js/app.js"></script>
<script src="https://kit.fontawesome.com/3b8c308efb.js" crossorigin="anonymous"></script>