<meta charset="utf-8">
<meta http-equiv="x-ua-compatible" content="ie=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title><?php echo APP::config('nazivAPP'); ?></title>
<link rel="stylesheet" href="<?php echo APP::config('url'); ?>public/css/foundation.css">
<link rel="stylesheet" href="<?php echo APP::config('url'); ?>public/css/app.css">
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
