<script src="<?php echo APP::config('url'); ?>public/js/vendor/jquery.js"></script>
<script src="<?php echo APP::config('url'); ?>public/js/vendor/what-input.js"></script>
<script src="<?php echo APP::config('url'); ?>public/js/vendor/foundation.js"></script>
<script src="<?php echo APP::config('url'); ?>public/js/app.js"></script>

<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
