<form class="log-in-form" method="POST"
action="/smjer/dodajnovi">
 <label>Naziv
    <input type="text" id="naziv" name="naziv" value="">
  </label>
  
  <label>Trajanje
    <input type="text" id="trajanje" name="trajanje" value="">
  </label>

  <label>Cijena
    <input type="text" id="cijena" name="cijena" value="">
  </label>

  <label>Upisnina
    <input type="text" id="upisnina" name="upisnina" value="">
  </label>

  <label for="verificiran">Verificiran</label>
  <select name="verificiran" id="verificiran">
    <option value="1">DA</option>
    <option value="0">NE</option>
  </select>

  <div class="grid-x grid-margin-x">
    <div class="large-6 cell">
      <a href="/smjer/index" class="alert button expanded">Odustani</a>
    </div>
    <div class="large-6 cell">
      <input type="submit" class="button expanded" value="Dodaj smjer"></input>
    </div>
  </div>
</form>
<?php echo $poruka; ?>