
<form action='/index/autorizacija' method='POST' accept-charset='UTF-8'>
<fieldset >
<legend>Prijava - <?php $poruka; ?></legend>

<label for='username' >Email*:</label>
<input type='email' name='email' id='email' value="<?php echo $email ?>"  maxlength="50" />

<label for='password' >Lozinka*:</label>
<input type='password' name='lozinka' id='lozinka' maxlength="50" />

<input type='submit' name='Submit' class="button expanded" value='Log in' />

</fieldset>
</form>

<?php $poruka; ?>