<!doctype html>
<html class="no-js" lang="en" dir="ltr">
  <head>
    <?php include_once 'Stranice/head.phtml'; ?>
  </head>
  <body>
    <div class="grid-container">
      <?php require_once 'Stranice/izbornik.phtml' ?>
      <!-- Početak tijela -->
      <div class="grid-x">
        <div class="large-12 small-12 columns">
          <div class="callout" style="min-height: 400px;"> 
            <?php 
                echo $sadrzaj;
             ?>
          </div>
        </div>
      </div>
      <!-- Kraj tijela -->
      <?php require_once 'Stranice/podnozje.phtml' ?>
    </div>
    <?php require_once 'Stranice/skripte.phtml' ?>
  </body>
</html>
